profile:
  name: base
  description: "Default offline sandbox with working directory access"

imports:
  system_profiles:
    - /System/Library/Sandbox/Profiles/bsd.sb

network:
  enabled: false
  allow_localhost: true

filesystem:
  default_deny: true

filesystem.read:
  paths:
    - /bin
    - /sbin
    - /usr/bin
    - /usr/sbin
    - /usr/local
    - /opt/local
    - /private/etc
    - /Library/Java/JavaVirtualMachines
    - /Library/Apple/usr/bin
    - /Library/Apple/usr/libexec/oah
    - /Library/Developer/CommandLineTools/
    - /opt/homebrew
  regex:
    - "/Users/[a-zA-Z]+/Library/Python/[0-9,\\.]+/lib/python[0-9,\\.]*/site-packages"
    - "/Users/[a-zA-Z]+/Library/Python/[0-9,\\.]+/bin"
    - "/Users/[a-zA-Z]+/.pyenv/versions/[0-9,\\.]+/lib/python[0-9,\\.]*/site-packages"
    - "/Users/[a-zA-Z]+/.pyenv/versions/[0-9,\\.]+/bin"

filesystem.write:
  paths:
    - "{home}/.m2"
    - "{home}/.rustup"
    - "{home}/.cargo"
    - "{home}/.rbenv"
    - "{home}/.yarnrc"
    - "{home}/.yarn"
    - "{home}/.cache/yarn"
    - "{home}/.config/yarn"
    - "{home}/.electron-gyp"
    - "{home}/Library/Caches/node-gyp"
    - "{home}/Library/Caches/electron"
    - "{home}/.pyenv/shims"
    - "{home}/Library/Caches/pip"
    - /private/var/run/utmpx
    - /private/etc/ssl/openssl.cnf
    - /private/var/folders/
    - /Applications/Xcode.app/
    - ~/.Library/Developer/Xcode/DerivedData
    - "{working-directory}"
  regex:
    - "^/dev/tty.*"
    - "{home}/.histfile.*"

process:
  allow_exec: true
  allow_fork: true

system:
  allow_user_preferences: true
  allow_sysctl_write: true
  allow_system_debug: true
  allow_mach_priv_task_port: true

mach:
  lookup:
    - com.apple.FSEvents

signal:
  target: children

